name: Bennett Building Co.
analytics:
  twitter: '#BennettBuildinCo '
github: true
description: >-
  official website of The Bennett Building Co., Damon Bennett provides
  consulting services for your construction & renovation projects.
author:
  name: Damon Bennett
  url: DamonBennett.ca
  email: DamonBennett@live.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.8041045
color:
  lightness: 0.9650742
  brandColors:
    - '#0A0A0A'
    - '#DD9A22'
    - '#2A1F0D'
    - '#8D6318'
    - '#654613'
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 0.9736842
content_rating:
  adult: false
typography_spectrum: 0.7402052
opengraph: {}
title: Construction & Renovation Consultations
